# Generated by Django 5.2.17 on 2026-09-24 19:34

import portal.fields
from django.db import migrations


def encrypt_existing(apps, schema_editor):
    """Re-save rows created before encryption: plaintext values are rewritten as ciphertext."""
    User = apps.get_model('portal', 'User')
    for user in User.objects.all().iterator():
        user.save(update_fields=['username', 'first_name', 'last_name', 'middle_name', 'email'])


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=portal.fields.EncryptedEmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=portal.fields.EncryptedCharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=portal.fields.EncryptedCharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=portal.fields.EncryptedCharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=portal.fields.EncryptedCharField(max_length=150, unique=True),
        ),
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]
